service: nearspark

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-2
  stage: prod
  stackName: xrcloud-nearspark
  memorySize: 128
  timeout: 15
  deploymentBucket:
    name: xrcloud-nearspark
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*

functions:
  thumbnail:
    handler: index.handler
    events:
      - http:
          method: get
          path: "thumbnail/{url}"
          request:
            parameters:
              paths:
                url: true
          contentHandling: CONVERT_TO_BINARY

plugins:
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  apigwBinary:
    types:
      - '*/*'

Outputs:
  NearsparkCloudfrontDistribution:
    Value:
      Fn::GetAtt: [ NearsparkCloudfrontDistribution, DomainName ]
